name: tunai_scan_qr
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/TunaiPackages/tunai_scan_qr.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
